# Default values for conanio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
web:
  replicaCount: 1
  image:
    repository: conanio-web
    pullPolicy: Never
    tag: latest
  service:
    type: ClusterIP
    port: 3000
server:
  replicaCount: 1
  image:
    repository: conanio-server
    pullPolicy: Never
    tag: latest
  service:
    type: ClusterIP
    port: 5000
