apiVersion: v1
kind: Service
metadata:
  name: {{ include "conanio.fullname" . }}-server
  labels:
    {{- include "conanio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "conanio.name" . }}-server
